name: Push Webhook

on:
  push:
    branches:
      - main
      - dev

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Send Discord message
        run: python .github/workflows/send_message.py
